name: Desktop

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 14.x

      - name: Prepare for app notarization
        if: startsWith(matrix.os, 'macos')
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.notarization_api_key }}' > ~/private_keys/AuthKey_${{ secrets.notarization_api_key_id }}.p8

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          package_root: 'packages/desktop'
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          # Code Signing
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

        env:
          # macOS notarization API key
          API_KEY_ID: ${{ secrets.notarization_api_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.notarization_api_key_issuer_id }}